# Дисциплина «Информационные технологии»

# Рабочая тетрадь № 2

### Ильин Сергей Сергеевич  БББО-07-20

# Оглавление

1. [Библиотека_NumPy](#1.-Библиотека_NumPy)
2. [Библиотека_Pandas](#2.-Библиотека_Pandas)
3. [Работа_числовыми_данными](#3.-Работа_числовыми_данными)

# 1. Библиотека_NumPy

In [19]:
# Пример 1.2.1
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


In [4]:
# Пример 1.2.2
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


In [12]:
# Пример 1.2.3
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.000688399120903016 0.9928718485427462 0.5281223464047061


In [13]:
# Пример 1.2.4
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
# Пример 1.2.5
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [15]:
# Пример 1.2.6
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [21]:
# Задание 1.3.1
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
# Задание 1.3.2
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [19]:
# Задание 1.3.3
array = np.random.randint(-10, 60, size=(3, 3, 3))
print(array)

[[[10 49  1]
  [ 0  0 25]
  [24 44 53]]

 [[-6 38 51]
  [ 7 29 19]
  [-1 21 33]]

 [[26 42 14]
  [13 -1 26]
  [24 10 58]]]


In [22]:
# Задание 1.3.4
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
# Задание 1.3.5
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr)[::-1])

[8 7 6 5 4 3 2 1]


In [41]:
# Задание 1.3.6
import numpy as np 
A = np.arange(25).reshape(5,5)
print(A)

np.prod(A.shape)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


25

# 2. Библиотека_Pandas

In [2]:
# Пример 2.2.1
import pandas as pd
import numpy as np
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


In [26]:
# Пример 2.2.2
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[1:])

1
5
1    4
2    3
3    2
4    1
dtype: int64


In [28]:
# Пример 2.2.3
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

In [2]:
# Пример 2.2.4
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)


Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [18]:
# Пример 2.2.5
dataframe.head(2)

year    name gender  count
0  2000   Emily      F  25956
1  2000  Hannah      F  23082

In [31]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [32]:
dataframe.shape

(1313, 6)

In [33]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [34]:
# Пример 2.2.6
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [35]:
# Пример 2.2.7
dataframe.loc[1:4]

Name PClass    Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [36]:
# Задание 2.3.1
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [12]:
import numpy as np
import pandas as pd
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([5, 4, 3, 2, 1])
square = np.square(a - b)
sum_square = np.sum(square)
distance = np.sqrt(sum_square)
print(distance)

6.324555320336759


In [1]:
# Задание 2.3.2
import numpy as np
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv'
dataframe = pd.read_csv(url)
dataframe

year     name gender  count
0       2000    Emily      F  25956
1       2000   Hannah      F  23082
2       2000  Madison      F  19968
3       2000   Ashley      F  17997
4       2000    Sarah      F  17702
...      ...      ...    ...    ...
624231  2018    Zylas      M      5
624232  2018    Zyran      M      5
624233  2018    Zyrie      M      5
624234  2018    Zyron      M      5
624235  2018    Zzyzx      M      5

[624236 rows x 4 columns]

In [2]:
# Задание 2.3.3
dataframe.head(2)

year    name gender  count
0  2000   Emily      F  25956
1  2000  Hannah      F  23082

In [3]:
dataframe.tail(3)

year   name gender  count
624233  2018  Zyrie      M      5
624234  2018  Zyron      M      5
624235  2018  Zzyzx      M      5

In [4]:
dataframe.shape

(624236, 4)

In [5]:
dataframe.describe()

year          count
count  624236.000000  624236.000000
mean     2009.115961     113.971929
std         5.383550     754.696900
min      2000.000000       5.000000
25%      2005.000000       7.000000
50%      2009.000000      11.000000
75%      2014.000000      29.000000
max      2018.000000   34477.000000

In [6]:
dataframe.iloc[1:5]

year     name gender  count
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

In [7]:
dataframe.loc[1:5]

year     name gender  count
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702
5  2000   Alexis      F  17629

# 3. Работа_числовыми_данными

In [13]:
# Пример 3.2.1
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [10]:
dataframe[dataframe['gender'] == 'F'].head(2)

year    name gender  count
0  2000   Emily      F  25956
1  2000  Hannah      F  23082

In [14]:
# Пример 3.2.2
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [15]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение", standardized.std())

Среднее: 0
Стандартное отклонение 1.0


In [21]:
# Пример 3.2.3
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                      'B':[103.02,107.26,110.35,114.23,114.68],
                      'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [20]:
# Задание 3.3.2
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)

minmax_scaler = MinMaxScaler()
z_scaler = StandardScaler()
dataframe[['sepal_length_cm']] = minmax_scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = z_scaler.fit_transform(dataframe[['sepal_width_cm']])
print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 