# РАБОЧАЯ ТЕТРАДЬ 2. ИЛЬИН СЕРГЕЙ БББО-07-20

## 1.1 Библиотека NumPy

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.

Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.

Наиболее важные атрибуты объектов ndarray:
    - ndarray.ndim - число измерений (чаще их называют "оси") массива.
    - ndarray.shape - размеры массива, его форма. Это кортеж натуральных
    чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
    и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
    - ndarray.size - количество элементов массива. Очевидно, равно
    произведению всех элементов атрибута shape.
    - ndarray.dtype - объект, описывающий тип элементов массива. Можно
    определить dtype, используя стандартные типы данных Python. NumPy здесь
    предоставляет целый букет возможностей, как встроенных, например: bool_,
    character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
    object_, так и возможность определить собственные типы данных, в том
    числе и составные.
    - ndarray.itemsize - размер каждого элемента массива в байтах.
    - ndarray.data - буфер, содержащий фактические элементы массива.
    Обычно не нужно использовать этот атрибут, так как обращаться к
    элементам массива проще всего с помощью индексов.


In [1]:
# TASK 1.3.1

import numpy as np
x = np.zeros((8,8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
# TASK 1.3.2

import numpy as np
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [3]:
# TASK 1.3.3

import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.69216609 0.01687667 0.22037989]
  [0.4901236  0.07791034 0.54964335]
  [0.85026356 0.81849218 0.06857091]]

 [[0.09205798 0.42449641 0.43053279]
  [0.28402557 0.25793486 0.22600335]
  [0.19986284 0.10634917 0.2166166 ]]

 [[0.60589183 0.70701475 0.00705589]
  [0.07098314 0.84560593 0.51848584]
  [0.11921786 0.78870799 0.92808131]]]


In [4]:
# TASK 1.3.4

import numpy as np
x = np.ones((8, 8), dtype = int)
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [5]:
# TASK 1.3.5

import numpy as np
x = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(x)[::-1])

[8 7 6 5 4 3 2 1]


In [6]:
# TASK 1.3.6

import numpy as np
x = np.zeros((10,10), dtype = int)
print(x)
print(x.shape)
print(x.size)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
(10, 10)
100


## 2.1 Библиотека Pandas

Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.

Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
    Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
    DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.


In [7]:
# TASK 2.3.1

import numpy as np
import pandas as pd
a = pd.Series([5, 7, 11, 18, 0, 2])
b = pd.Series([6, 9, 15, 33, 16, 3])
x = np.linalg.norm(a-b)
print(x)

22.427661492005804


In [8]:
# TASK 2.3.2

import pandas as pd
data={'stream':['false','true','true','false','false','true','true'],
'slope':['steep','moderate','steep','steep','flat','steep','steep'],
'elevation':['high','low','medium','medium','high','highest','hgih'],
'vegetation':['chapparal','riparian','riparian','chapparal','conifer','conifer','chapparal']}
data={'stream':['false','true','true','false','false','true','true'],
'slope':['steep','moderate','steep','steep','flat','steep','steep'],
'elevation':['high','low','medium','medium','high','highest','hgih'],
'vegetation':['chapparal','riparian','riparian','chapparal','conifer','conifer','chapparal']}
df=pd.DataFrame(data)
df

stream     slope elevation vegetation
0  false     steep      high  chapparal
1   true  moderate       low   riparian
2   true     steep    medium   riparian
3  false     steep    medium  chapparal
4  false      flat      high    conifer
5   true     steep   highest    conifer
6   true     steep      hgih  chapparal

In [9]:
# TASK 2.3.3

import pandas as pd
data={'stream':['false','true','true','false','false','true','true'],
'slope':['steep','moderate','steep','steep','flat','steep','steep'],
'elevation':['high','low','medium','medium','high','highest','hgih'],
'vegetation':['chapparal','riparian','riparian','chapparal','conifer','conifer','chapparal']}
data={'stream':['false','true','true','false','false','true','true'],
'slope':['steep','moderate','steep','steep','flat','steep','steep'],
'elevation':['high','low','medium','medium','high','highest','hgih'],
'vegetation':['chapparal','riparian','riparian','chapparal','conifer','conifer','chapparal']}
df=pd.DataFrame(data)

print(df.head(2))
print(df.tail(3))
print(df.shape)
print(df.describe())

df[df['vegetation'] == 'chapparal'].head(3)

  stream     slope elevation vegetation
0  false     steep      high  chapparal
1   true  moderate       low   riparian
  stream  slope elevation vegetation
4  false   flat      high    conifer
5   true  steep   highest    conifer
6   true  steep      hgih  chapparal
(7, 4)
       stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         5          3
top      true  steep      high  chapparal
freq        4      5         2          3


stream  slope elevation vegetation
0  false  steep      high  chapparal
3  false  steep    medium  chapparal
6   true  steep      hgih  chapparal

## 3.1 Работа с числовыми данными

Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.

На практике наиболее распространены следующие методы
нормализации признаков:
    Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
    Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.

При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

In [2]:
# TASK 3.1.2

import pandas as pd
import numpy as np
from sklearn import preprocessing

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scalerZ = preprocessing.StandardScaler()
dataframe[["sepal_length_cm"]]=scaler.fit_transform(dataframe[["sepal_length_cm"]])
dataframe[["sepal_width_cm"]]=scalerZ.fit_transform(dataframe[["sepal_width_cm"]])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]